/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJERCICIO2B_H_RPCGEN
#define _EJERCICIO2B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define EJ2 0x20000001
#define EJ2VER1 1

#if defined(__STDC__) || defined(__cplusplus)
#define F1 1
extern  float * f1_1(void *, CLIENT *);
extern  float * f1_1_svc(void *, struct svc_req *);
extern int ej2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define F1 1
extern  float * f1_1();
extern  float * f1_1_svc();
extern int ej2_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJERCICIO2B_H_RPCGEN */
