/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Ej7.h"

bool_t
xdr_spectime (XDR *xdrs, spectime *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->tv_nsec))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->tv_sec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_respuesta (XDR *xdrs, respuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_spectime (xdrs, &objp->tSv))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->t1))
		 return FALSE;
	return TRUE;
}
