.PHONY: all
all: Ejercicio10Cliente.class Ejercicio10Servidor.class Ejercicio10HiloServidor.class
.PHONY: clean
clean :
	rm Ejercicio10Servidor.class Ejercicio10Cliente.class Ejercicio10HiloServidor.class
Ejercicio10Cliente.class : Ejercicio10Cliente.java
	javac Ejercicio10Cliente.java
Ejercicio10Servidor.class : Ejercicio10Servidor.java
	javac Ejercicio10Servidor.java
Ejercicio10HiloServidor.class : Ejercicio10HiloServidor.java
	javac Ejercicio10HiloServidor.java
