/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMAARREGLOS_H_RPCGEN
#define _SUMAARREGLOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TAMANO 2048

typedef char *nametype;

#define SUMAARREGLOS 0x200F0002
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define cadena 1
extern  nametype * cadena_1(nametype *, CLIENT *);
extern  nametype * cadena_1_svc(nametype *, struct svc_req *);
extern int sumaarreglos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cadena 1
extern  nametype * cadena_1();
extern  nametype * cadena_1_svc();
extern int sumaarreglos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);

#else /* K&R C */
extern bool_t xdr_nametype ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMAARREGLOS_H_RPCGEN */
