/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "SumaArreglos.h"

bool_t
xdr_nametype (XDR *xdrs, nametype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAMANO))
		 return FALSE;
	return TRUE;
}
