/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJ5_H_RPCGEN
#define _EJ5_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct st_hora {
	int8_t segundo;
	int8_t minuto;
	int8_t hora;
};
typedef struct st_hora st_hora;

struct st_dia {
	int8_t dia;
	int8_t mes;
	int16_t anho;
};
typedef struct st_dia st_dia;

typedef struct parametros arregloFloats;

struct parametros {
	int cant;
	float arr[4];
};
typedef struct parametros parametros;

#define MINIOPS 0x200F0003
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define decToBin 1
extern  int * dectobin_1(int *, CLIENT *);
extern  int * dectobin_1_svc(int *, struct svc_req *);
#define binToHex 2
extern  int * bintohex_1(int *, CLIENT *);
extern  int * bintohex_1_svc(int *, struct svc_req *);
#define pesoADolar 3
extern  float * pesoadolar_1(float *, CLIENT *);
extern  float * pesoadolar_1_svc(float *, struct svc_req *);
#define pesoAEuro 4
extern  float * pesoaeuro_1(float *, CLIENT *);
extern  float * pesoaeuro_1_svc(float *, struct svc_req *);
#define f_hora 5
extern  st_hora * f_hora_1(void *, CLIENT *);
extern  st_hora * f_hora_1_svc(void *, struct svc_req *);
#define f_dia 6
extern  st_dia * f_dia_1(void *, CLIENT *);
extern  st_dia * f_dia_1_svc(void *, struct svc_req *);
#define suma 7
extern  float * suma_1(arregloFloats *, CLIENT *);
extern  float * suma_1_svc(arregloFloats *, struct svc_req *);
#define multiplicacion 10
extern  float * multiplicacion_1(arregloFloats *, CLIENT *);
extern  float * multiplicacion_1_svc(arregloFloats *, struct svc_req *);
extern int miniops_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define decToBin 1
extern  int * dectobin_1();
extern  int * dectobin_1_svc();
#define binToHex 2
extern  int * bintohex_1();
extern  int * bintohex_1_svc();
#define pesoADolar 3
extern  float * pesoadolar_1();
extern  float * pesoadolar_1_svc();
#define pesoAEuro 4
extern  float * pesoaeuro_1();
extern  float * pesoaeuro_1_svc();
#define f_hora 5
extern  st_hora * f_hora_1();
extern  st_hora * f_hora_1_svc();
#define f_dia 6
extern  st_dia * f_dia_1();
extern  st_dia * f_dia_1_svc();
#define suma 7
extern  float * suma_1();
extern  float * suma_1_svc();
#define multiplicacion 10
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
extern int miniops_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_st_hora (XDR *, st_hora*);
extern  bool_t xdr_st_dia (XDR *, st_dia*);
extern  bool_t xdr_arregloFloats (XDR *, arregloFloats*);
extern  bool_t xdr_parametros (XDR *, parametros*);

#else /* K&R C */
extern bool_t xdr_st_hora ();
extern bool_t xdr_st_dia ();
extern bool_t xdr_arregloFloats ();
extern bool_t xdr_parametros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJ5_H_RPCGEN */
