/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJ5_H_RPCGEN
#define _EJ5_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct st_hora {
	int segundo;
	int minuto;
	int hora;
};
typedef struct st_hora st_hora;

struct st_dia {
	int dia;
	int mes;
	int anho;
};
typedef struct st_dia st_dia;

typedef struct parametros arregloFloats;

struct parametros {
	int cant;
	float arr[4];
};
typedef struct parametros parametros;

#define MINIOPS 0x200F0003
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define dectobin 1
extern  char ** dectobin_1(char **, CLIENT *);
extern  char ** dectobin_1_svc(char **, struct svc_req *);
#define bintohex 2
extern  char ** bintohex_1(char **, CLIENT *);
extern  char ** bintohex_1_svc(char **, struct svc_req *);
#define pesoadolar 3
extern  float * pesoadolar_1(float *, CLIENT *);
extern  float * pesoadolar_1_svc(float *, struct svc_req *);
#define pesoaeuro 4
extern  float * pesoaeuro_1(float *, CLIENT *);
extern  float * pesoaeuro_1_svc(float *, struct svc_req *);
#define f_hora 5
extern  st_hora * f_hora_1(void *, CLIENT *);
extern  st_hora * f_hora_1_svc(void *, struct svc_req *);
#define f_dia 6
extern  st_dia * f_dia_1(void *, CLIENT *);
extern  st_dia * f_dia_1_svc(void *, struct svc_req *);
#define suma 7
extern  float * suma_1(arregloFloats *, CLIENT *);
extern  float * suma_1_svc(arregloFloats *, struct svc_req *);
#define resta 8
extern  float * resta_1(arregloFloats *, CLIENT *);
extern  float * resta_1_svc(arregloFloats *, struct svc_req *);
#define multiplicacion 9
extern  float * multiplicacion_1(arregloFloats *, CLIENT *);
extern  float * multiplicacion_1_svc(arregloFloats *, struct svc_req *);
#define division 10
extern  float * division_1(arregloFloats *, CLIENT *);
extern  float * division_1_svc(arregloFloats *, struct svc_req *);
extern int miniops_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define dectobin 1
extern  char ** dectobin_1();
extern  char ** dectobin_1_svc();
#define bintohex 2
extern  char ** bintohex_1();
extern  char ** bintohex_1_svc();
#define pesoadolar 3
extern  float * pesoadolar_1();
extern  float * pesoadolar_1_svc();
#define pesoaeuro 4
extern  float * pesoaeuro_1();
extern  float * pesoaeuro_1_svc();
#define f_hora 5
extern  st_hora * f_hora_1();
extern  st_hora * f_hora_1_svc();
#define f_dia 6
extern  st_dia * f_dia_1();
extern  st_dia * f_dia_1_svc();
#define suma 7
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 8
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplicacion 9
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define division 10
extern  float * division_1();
extern  float * division_1_svc();
extern int miniops_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_st_hora (XDR *, st_hora*);
extern  bool_t xdr_st_dia (XDR *, st_dia*);
extern  bool_t xdr_arregloFloats (XDR *, arregloFloats*);
extern  bool_t xdr_parametros (XDR *, parametros*);

#else /* K&R C */
extern bool_t xdr_st_hora ();
extern bool_t xdr_st_dia ();
extern bool_t xdr_arregloFloats ();
extern bool_t xdr_parametros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJ5_H_RPCGEN */
