/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Ej5.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
miniops_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *dectobin_1_arg;
		char *bintohex_1_arg;
		float pesoadolar_1_arg;
		float pesoaeuro_1_arg;
		arregloFloats suma_1_arg;
		arregloFloats resta_1_arg;
		arregloFloats multiplicacion_1_arg;
		arregloFloats division_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case dectobin:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) dectobin_1_svc;
		break;

	case bintohex:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) bintohex_1_svc;
		break;

	case pesoadolar:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) pesoadolar_1_svc;
		break;

	case pesoaeuro:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) pesoaeuro_1_svc;
		break;

	case f_hora:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_st_hora;
		local = (char *(*)(char *, struct svc_req *)) f_hora_1_svc;
		break;

	case f_dia:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_st_dia;
		local = (char *(*)(char *, struct svc_req *)) f_dia_1_svc;
		break;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_arregloFloats;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) suma_1_svc;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_arregloFloats;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) resta_1_svc;
		break;

	case multiplicacion:
		_xdr_argument = (xdrproc_t) xdr_arregloFloats;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) multiplicacion_1_svc;
		break;

	case division:
		_xdr_argument = (xdrproc_t) xdr_arregloFloats;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) division_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MINIOPS, VERSION1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIOPS, VERSION1, miniops_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MINIOPS, VERSION1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIOPS, VERSION1, miniops_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MINIOPS, VERSION1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
