/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Ej5.h"

bool_t
xdr_st_hora (XDR *xdrs, st_hora *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->segundo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->minuto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hora))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_st_dia (XDR *xdrs, st_dia *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dia))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anho))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arregloFloats (XDR *xdrs, arregloFloats *objp)
{
	register int32_t *buf;

	 if (!xdr_parametros (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_parametros (XDR *xdrs, parametros *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 4,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
